---
- name: chech config
  hosts: switches
  gather_facts: no

  tasks:
    - name: configurable backup path
      ios_config:
        backup: yes
        backup_options:
          filename: backup-teste.cfg
          dir_path: /home/willian/backups
