---
- name: First Play
  hosts: roteadores
  gather_facts: False
  connection: local
  tasks:
    - name: run commands that require answering a prompt
      ios_command:
         commands:
         - command: clear counters e0/0
           prompt: Clear "show interface" counters on this interface \[confirm\]
           answer: y

