---
- name: First Play
  hosts: roteadores
  gather_facts: False
  connection: local
  tasks:
    - name: removendo todos os usuario exceto admin e usuarios listados...
      ios_user:
        aggregate:
        - name: usuario1
        - name: usuario2
        purge: yes
